### PR TITLE
testing using Test Kitchen, testinfra, and Docker

### PR DESCRIPTION
**Pull request by blbradley**
This will fail because of #17. I could fix it here or in another PR.

### CODE REVIEW

**Comment by gravyboat** [comment]
Thanks for this one. The issues are different enough to be in two different PRs. I'm going to merge this one for now, feel free to open a fix for #17!

**Comment by blbradley** [comment]
No problem. Thank you!

P.S. Use squash and merge when it makes sense! Single commits are a great time to use it.

**Comment by gravyboat** [comment]
Squash and merge is the default now option on most PRs now, pretty sure that's what I did here but maybe not.

**Comment by blbradley** [comment]
It becomes the default option when you do it the first time per repo (I think). No worries.

**Pull request merged**
